include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'


stages:
  - check
  - build
  - deploy


variables:
  PIO_LIB_FOLDER: libneon


.rules-changes-sources: &rules-changes-sources
  changes:
    - ${PIO_LIB_FOLDER}/src/**/*
    - ${PIO_LIB_FOLDER}/include/**/*
    - ${PIO_LIB_FOLDER}/examples/**/*
    - cicd/platformio.ini

.rules-changes-cicd: &rules-changes-cicd
  changes:
    - cicd/*
    - .gitlab-ci.yml

.rules-merge-to-master: &rules-merge-to-master
  if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  when: always


check format:
  stage: check
  image: alpine
  allow_failure: true
  before_script:
    - apk add --update --no-cache git clang clang-extra-tools
  script:
    - >
      find . -not -path '*/\.*' -and \( -name '*.[hc]' -or -name '*.[hc]pp' \) | while read -r FILE; do
          echo "Formatting $FILE"
          clang-format --style file -i "$FILE"
      done
    - git diff --patch | tee 0001-Clang-format.patch
    - test ! -s 0001-Clang-format.patch
  artifacts:
    paths:
      - 0001-Clang-format.patch
    expire_in: 1 week
    when: on_failure
  rules:
    # Run always, on merge request too
    - when: always


build examples:
  image: ${CI_REGISTRY}/proj/testinator/esp32:latest
  stage: build
  script:
    - >
      for file in ${PIO_LIB_FOLDER}/examples/*.cpp; do
        BUILD_DIR="$(mktemp -d)"
        pio ci \
          --build-dir="${BUILD_DIR}" \
          --project-conf=cicd/platformio.ini \
          --lib=${PIO_LIB_FOLDER} \
          --keep-build-dir \
          $file
        rm -rf "${BUILD_DIR}"
      done
  rules:
    # [skip examples] tag for skipping
    - if: '$CI_COMMIT_MESSAGE =~ /skip examples/'
      when: never
    # Run on merge request
    - <<: *rules-merge-to-master
    # But skip by default if the sources did not change
    - <<: *rules-changes-sources
    - <<: *rules-changes-cicd


publish library:
  image: ${CI_REGISTRY}/proj/testinator/esp32:latest
  stage: deploy
  before_script:
    - python3 -m pip install --user gitpython
  script:
    - |
      python3 cicd/check_version.py ${PIO_LIB_FOLDER}/library.json && \
      pio package publish --owner ${PLATFORMIO_ORG} --non-interactive ${PIO_LIB_FOLDER}
  only:
    - tags
  except:
    - branches
